2020-07-23 14:21:37.387|ERROR|_func_exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 147, in _func
    logging.exception('%s_exception', func.__name__)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 144, in _func
    response = func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 133, in _func
    return func(request, data, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_lib/preprocessor.py", line 35, in _func
    return func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_api/views/monster_api.py", line 162, in get_metadata
    monster_dcl_data = ema_monster_manager.get_monster_dcl_data(monster_id)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_lib/ema_monster_manager.py", line 106, in get_monster_dcl_data
    return EtheremonDB.DclMonsterData.objects.filter(Mon_ID=monster_id).first()
AttributeError: class EtheremonDB has no attribute 'DclMonsterData'

2020-07-23 14:24:59.753|ERROR|_func_exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 147, in _func
    logging.exception('%s_exception', func.__name__)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 144, in _func
    response = func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 133, in _func
    return func(request, data, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_lib/preprocessor.py", line 35, in _func
    return func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_api/views/monster_api.py", line 181, in get_metadata
    dcl_level = get_level(monster_dcl_data.dxp)
AttributeError: 'NoneType' object has no attribute 'dxp'

2020-07-23 14:25:51.582|ERROR|_func_exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 147, in _func
    logging.exception('%s_exception', func.__name__)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 144, in _func
    response = func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 133, in _func
    return func(request, data, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_lib/preprocessor.py", line 35, in _func
    return func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_api/views/monster_api.py", line 182, in get_metadata
    dcl_level = get_level(monster_dcl_data.dxp)
AttributeError: 'NoneType' object has no attribute 'dxp'

2020-07-23 14:26:07.930|ERROR|_func_exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/emenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 147, in _func
    logging.exception('%s_exception', func.__name__)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 144, in _func
    response = func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/common/django_utils.py", line 133, in _func
    return func(request, data, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_lib/preprocessor.py", line 35, in _func
    return func(request, *args, **kwargs)
  File "/home/aayushpy/Desktop/ethermon-backend/etheremon_api/views/monster_api.py", line 182, in get_metadata
    dcl_level = get_level(monster_dcl_data.dxp)
AttributeError: 'NoneType' object has no attribute 'dxp'

